In [21]:
import numpy as np
import pandas as pd

In [22]:
# Datatypes
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

In [23]:
dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

In [24]:
x = np.array([1,2,3,6,8,8],dtype='f4')
x

array([1., 2., 3., 6., 8., 8.], dtype=float32)

In [25]:
x.dtype

dtype('float32')

In [26]:
x.astype(float)

array([1., 2., 3., 6., 8., 8.])

In [27]:
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr = np.array(range(1,20,2))
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [30]:
# Create an array evenly spaced in specific intervals
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [40]:
# Create the array with 0
np.zeros((2,3),dtype='i4')

array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
# Create the array with 1
np.ones((3,3),dtype='i4')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [36]:
np.random.rand(3,3)

array([[0.30740291, 0.75349761, 0.1392003 ],
       [0.29921945, 0.63320058, 0.15366258],
       [0.15594596, 0.92845549, 0.71196453]])

In [42]:
np.random.randint((2,3))

array([0, 1])

In [43]:
np.empty_like(arr)

array([         0,          0, 1678237504,        492, 1678237760,
              492, 1678238336,        492,        114,    9532160])

In [46]:
# Create the array with constant value
np.full((2,3),fill_value=5)

array([[5, 5, 5],
       [5, 5, 5]])

In [49]:
# create an array using repetation
arr = [0,1,2]
np.repeat(arr, 4)

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [50]:
# Create identity matrix
np.identity(3,dtype='i4')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
# Sampling method 
# set seed
a1 = np.random.seed(123)
a1

In [58]:
# Set random independent state
a2 = np.random.RandomState(321)
a2.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

In [60]:
# Genrate a random sample from interval [0:1]
np.random.rand(3)

array([0.28613933, 0.22685145, 0.55131477])

In [62]:
np.random.rand(3,3)

array([[0.71946897, 0.42310646, 0.9807642 ],
       [0.68482974, 0.4809319 , 0.39211752],
       [0.34317802, 0.72904971, 0.43857224]])

In [81]:
arr = np.random.randint(1,100,10,dtype='i8')

In [78]:
# Create float random values
np.random.rand(10)

array([0.28678709, 0.99173191, 0.5604223 , 0.78781743, 0.03248247,
       0.08407621, 0.1092332 , 0.01528584, 0.92197897, 0.25363529])

In [79]:
np.random.ranf(10)

array([0.99656913, 0.73812985, 0.25061079, 0.99180464, 0.86853386,
       0.16499801, 0.18532191, 0.68018614, 0.07828025, 0.58452486])

In [82]:
np.info(arr)

class:  ndarray
shape:  (10,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x1ec63ce07a0
byteorder:  little
byteswap:  False
type: int64


In [83]:
arr.shape

(10,)

In [84]:
len(arr)

10

In [85]:
arr/0

C:\Users\user\AppData\Local\Temp\ipykernel_11456\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [86]:
arr/2

array([30. ,  3.5, 28. , 25. , 42.5, 15. , 19.5, 31.5, 13.5, 45. ])

In [88]:
# Exponential value
np.exp(arr)

array([1.14200739e+26, 1.09663316e+03, 2.09165950e+24, 5.18470553e+21,
       8.22301271e+36, 1.06864746e+13, 8.65934004e+16, 2.29378316e+27,
       5.32048241e+11, 1.22040329e+39])

In [89]:
np.log(arr)

array([4.09434456, 1.94591015, 4.02535169, 3.91202301, 4.44265126,
       3.40119738, 3.66356165, 4.14313473, 3.29583687, 4.49980967])

In [90]:
np.log10(arr)

array([1.77815125, 0.84509804, 1.74818803, 1.69897   , 1.92941893,
       1.47712125, 1.59106461, 1.79934055, 1.43136376, 1.95424251])

In [91]:
np.log2(arr)

array([5.9068906 , 2.80735492, 5.80735492, 5.64385619, 6.40939094,
       4.9068906 , 5.28540222, 5.97727992, 4.7548875 , 6.4918531 ])

In [92]:
np.sqrt(arr)

array([7.74596669, 2.64575131, 7.48331477, 7.07106781, 9.21954446,
       5.47722558, 6.244998  , 7.93725393, 5.19615242, 9.48683298])

In [93]:
np.sin(arr) 

array([-0.30481062,  0.6569866 , -0.521551  , -0.26237485, -0.17607562,
       -0.98803162,  0.96379539,  0.1673557 ,  0.95637593,  0.89399666])

In [95]:
np.cos(arr)

array([-0.95241298,  0.75390225,  0.85322011,  0.96496603, -0.98437664,
        0.15425145,  0.26664293,  0.98589658, -0.29213881, -0.44807362])

In [101]:
# Row wise sum
np.sum(arr,axis=0)

array([12, 15, 18])

In [107]:
# Column wise sum
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [108]:
np.max(arr,axis=0)

array([7, 8, 9])

In [109]:
np.max(arr,axis=1)

array([3, 6, 9])

In [110]:
np.min(arr,axis=0)

array([1, 2, 3])

In [111]:
np.min(arr,axis=1)

array([1, 4, 7])

In [112]:
np.median(arr)

5.0

In [113]:
np.var(arr)

6.666666666666667

In [117]:
a= np.random.rand(5,5)

In [118]:
a

array([[0.19343956, 0.7615944 , 0.41662288, 0.92204196, 0.62605039],
       [0.45038011, 0.84002956, 0.40209975, 0.63358524, 0.58976986],
       [0.84261652, 0.2056685 , 0.43510328, 0.88369785, 0.7287074 ],
       [0.60249629, 0.70629353, 0.28644783, 0.42298616, 0.32899685],
       [0.92506611, 0.99737696, 0.86469702, 0.74175497, 0.88661767]])

In [120]:
np.sort(a,axis=0)

array([[0.19343956, 0.2056685 , 0.28644783, 0.42298616, 0.32899685],
       [0.45038011, 0.70629353, 0.40209975, 0.63358524, 0.58976986],
       [0.60249629, 0.7615944 , 0.41662288, 0.74175497, 0.62605039],
       [0.84261652, 0.84002956, 0.43510328, 0.88369785, 0.7287074 ],
       [0.92506611, 0.99737696, 0.86469702, 0.92204196, 0.88661767]])

In [121]:
np.sort(a,axis=1)

array([[0.19343956, 0.41662288, 0.62605039, 0.7615944 , 0.92204196],
       [0.40209975, 0.45038011, 0.58976986, 0.63358524, 0.84002956],
       [0.2056685 , 0.43510328, 0.7287074 , 0.84261652, 0.88369785],
       [0.28644783, 0.32899685, 0.42298616, 0.60249629, 0.70629353],
       [0.74175497, 0.86469702, 0.88661767, 0.92506611, 0.99737696]])

In [122]:
np.transpose(a)

array([[0.19343956, 0.45038011, 0.84261652, 0.60249629, 0.92506611],
       [0.7615944 , 0.84002956, 0.2056685 , 0.70629353, 0.99737696],
       [0.41662288, 0.40209975, 0.43510328, 0.28644783, 0.86469702],
       [0.92204196, 0.63358524, 0.88369785, 0.42298616, 0.74175497],
       [0.62605039, 0.58976986, 0.7287074 , 0.32899685, 0.88661767]])

In [124]:
## Flatterning an array
a.flatten()

array([0.19343956, 0.7615944 , 0.41662288, 0.92204196, 0.62605039,
       0.45038011, 0.84002956, 0.40209975, 0.63358524, 0.58976986,
       0.84261652, 0.2056685 , 0.43510328, 0.88369785, 0.7287074 ,
       0.60249629, 0.70629353, 0.28644783, 0.42298616, 0.32899685,
       0.92506611, 0.99737696, 0.86469702, 0.74175497, 0.88661767])

In [125]:
arr1 = np.random.rand(5,5)

In [126]:
arr2 = np.random.rand(5,5)

In [129]:
# Method 1
arr1.dot(arr2)

array([[1.24334413, 0.74495894, 1.75791871, 0.72768134, 1.36354938],
       [1.03632847, 0.59735123, 1.52938966, 0.6338594 , 1.17613335],
       [1.3920705 , 0.92033759, 1.87042488, 0.91253534, 1.21126656],
       [0.19595011, 0.27943122, 0.78752583, 0.24515818, 0.72079917],
       [1.50257356, 1.08780819, 2.67711718, 1.11632623, 1.91243904]])

In [130]:
# Method 2
np.dot(arr1,arr2)

array([[1.24334413, 0.74495894, 1.75791871, 0.72768134, 1.36354938],
       [1.03632847, 0.59735123, 1.52938966, 0.6338594 , 1.17613335],
       [1.3920705 , 0.92033759, 1.87042488, 0.91253534, 1.21126656],
       [0.19595011, 0.27943122, 0.78752583, 0.24515818, 0.72079917],
       [1.50257356, 1.08780819, 2.67711718, 1.11632623, 1.91243904]])

In [131]:
# Method 3
arr1 @ arr2

array([[1.24334413, 0.74495894, 1.75791871, 0.72768134, 1.36354938],
       [1.03632847, 0.59735123, 1.52938966, 0.6338594 , 1.17613335],
       [1.3920705 , 0.92033759, 1.87042488, 0.91253534, 1.21126656],
       [0.19595011, 0.27943122, 0.78752583, 0.24515818, 0.72079917],
       [1.50257356, 1.08780819, 2.67711718, 1.11632623, 1.91243904]])

In [133]:
# Eigen value
w ,v=np.linalg.eig(arr1)

In [134]:
print(w)
print(v)

[ 2.30689754+0.j         -0.41755543+0.13684494j -0.41755543-0.13684494j
  0.25687172+0.j          0.07708087+0.j        ]
[[-0.46436961+0.j         -0.43108413+0.06352451j -0.43108413-0.06352451j
   0.65940549+0.j          0.83332298+0.j        ]
 [-0.3976955 +0.j         -0.55084579-0.06137894j -0.55084579+0.06137894j
   0.39845096+0.j          0.27268699+0.j        ]
 [-0.38163677+0.j          0.68136009+0.j          0.68136009-0.j
   0.16881867+0.j         -0.06781115+0.j        ]
 [-0.25783029+0.j         -0.05719562+0.14889654j -0.05719562-0.14889654j
  -0.55041111+0.j         -0.44702046+0.j        ]
 [-0.64348743+0.j          0.06201274-0.0969226j   0.06201274+0.0969226j
  -0.27380485+0.j         -0.1636734 +0.j        ]]


In [135]:
np.linalg.det(arr1)

0.008819144092332792

In [136]:
np.linalg.inv(arr1)

array([[ 17.3642608 , -23.57161318,  -8.37479193,  -8.90920164,
         10.88657806],
       [  6.00672499,  -6.99274232,  -0.36652945,  -1.28829939,
          0.98848766],
       [ -3.22836417,   5.68855293,   0.47443077,  -0.24491444,
         -1.11212526],
       [ -8.67566777,  10.14264364,   3.67768852,   3.71210404,
         -3.50253355],
       [ -2.50261785,   3.37843029,   1.20780123,   2.54221981,
         -1.58341686]])

In [141]:
# Linear Equation
y = [1,2,3,4,5]
solution,residual,rank,singular =  np.linalg.lstsq(arr1,y)

C:\Users\user\AppData\Local\Temp\ipykernel_11456\3712932307.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solution,residual,rank,singular =  np.linalg.lstsq(arr1,y)


In [143]:
print(solution)
print(residual)
print(rank)
print(singular)

[-36.10725762  -9.28910725   3.03174991  19.97843349  10.12944136]
[]
5
[2.4093899  1.03096988 0.53644658 0.25487429 0.02596695]


# Pandas Library

In [145]:
data1 = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}

In [148]:
df = pd.DataFrame(data1)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [149]:
df.head()

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [150]:
df.tail()

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [151]:
df[1:3]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [152]:
df[1:-3]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [153]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [154]:
df['day']

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [158]:
df[['day','temperature']]

day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

In [160]:
df.temperature.max()

35

In [161]:
# Calculate the temperature greater than 30
df.iloc[np.where(df.temperature > 30)]

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [162]:
df[df.temperature > 31]

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [164]:
# Calculate the days in which temperature is 32
df[df.temperature == 32]

day  temperature  windspeed event
0  1/1/2017           32          6  Rain
4  1/5/2017           32          4  Rain

In [169]:
df[df.temperature ==  df.temperature.min()].event

3    Snow
Name: event, dtype: object

In [170]:
# Setting an index
df.set_index('day')

temperature  windspeed  event
day                                    
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [171]:
df.set_index('event')

day  temperature  windspeed
event                                  
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [174]:
df.loc[0]

day            1/1/2017
temperature          32
windspeed             6
event              Rain
Name: 0, dtype: object

In [175]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [176]:
df.set_index('event',inplace=True)

In [177]:
df.index

Index(['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny'], dtype='object', name='event')

In [179]:
df.loc['Snow']

day  temperature  windspeed
event                                  
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

In [180]:
df.reset_index(inplace=True)

In [183]:
df = pd.read_csv('Day11.csv')
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [186]:
df1 = pd.read_excel('Day12.xlsx')
df1

day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [187]:
data2 = {
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain', 'Sunny', 'Snow']
}

In [189]:
df2 = pd.DataFrame(data2)
df2

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [190]:
data3 = [
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]

In [192]:
df3 = pd.DataFrame(data3)
df3

0   1  2      3
0  1/1/2017  32  6   Rain
1  1/2/2017  35  7  Sunny
2  1/3/2017  28  2   Snow

In [193]:
data4 = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
    
]

In [195]:
df4 = pd.DataFrame(data4)
df4

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

# Series data Structure --------------------------------

In [197]:
obj = pd.Series([1,"Anuraj",3.5,"Nigade"])
obj

0         1
1    Anuraj
2       3.5
3    Nigade
dtype: object

In [198]:
obj[1]

'Anuraj'

In [199]:
obj.values

array([1, 'Anuraj', 3.5, 'Nigade'], dtype=object)

RangeIndex(start=0, stop=4, step=1)

In [201]:
obj = pd.Series([1,"Anuraj",3.5,"Nigade"],index=["a",'b','c','d'])
obj

a         1
b    Anuraj
c       3.5
d    Nigade
dtype: object

In [205]:
obj['b']

'Anuraj'

In [211]:
sinfo = {
    'Anuraj':96,'Chirag':97,'Shubham':98}

In [212]:
s = pd.Series(sinfo)
s

Anuraj     96
Chirag     97
Shubham    98
dtype: int64

In [213]:
s['Shubham']

98

In [214]:
# Print the marks > 80
s[s > 97]

Shubham    98
dtype: int64

In [215]:
s['Chirag'] = 110

In [216]:
s

Anuraj      96
Chirag     110
Shubham     98
dtype: int64

In [217]:
"sai" in s

False