In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder,PolynomialFeatures,StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
%matplotlib inline

In [3]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,recall_score,precision_score,f1_score


In [4]:
df = pd.read_csv('classification.csv')

In [5]:
df.sample(10)

Obs   Outlook Temperature Humidity    Wind Play Tennis
12   13  Overcast         Hot   Normal    Weak         Yes
13   14      Rain        Mild     High  Strong          No
9    10      Rain        Mild   Normal    Weak         Yes
2     3  Overcast         Hot     High    Weak         Yes
11   12  Overcast        Mild     High  Strong         Yes
3     4      Rain        Mild     High    Weak         Yes
1     2     Sunny         Hot     High  Strong          No
5     6      Rain        Cool   Normal  Strong          No
7     8     Sunny        Mild     High    Weak          No
6     7  Overcast        Cool   Normal  Strong         Yes

In [6]:
df = df.drop('Obs',axis=1)

In [7]:
df['Play Tennis'].replace({'No':0,'Yes':1},inplace=True)

In [8]:
df.columns

Index(['Outlook', 'Temperature', 'Humidity', 'Wind', 'Play Tennis'], dtype='object')

In [9]:
df1 = pd.get_dummies(data=df,columns=['Outlook', 'Humidity', 'Wind'])
df1.columns

Index(['Temperature', 'Play Tennis', 'Outlook_Overcast', 'Outlook_Rain',
       'Outlook_Sunny', 'Humidity_High', 'Humidity_Normal', 'Wind_Strong',
       'Wind_Weak'],
      dtype='object')

In [24]:
lecoder = OneHotEncoder()
df2 = lecoder.fit_transform(df[['Outlook', 'Temperature', 'Humidity', 'Wind']]).toarray()

In [10]:
X = df1.drop(['Temperature', 'Play Tennis'],axis=1).astype('int')
Y = df1['Play Tennis']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [12]:
DT = DecisionTreeClassifier(criterion='entropy',random_state=0)
DT.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [14]:
y_pred = DT.predict(X_test)
y_pred

array([1, 1, 1, 0, 1], dtype=int64)

In [16]:
confusion_matrix(y_test,y_pred)

array([[0, 0],
       [1, 4]], dtype=int64)

In [15]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.80      0.89         5

    accuracy                           0.80         5
   macro avg       0.50      0.40      0.44         5
weighted avg       1.00      0.80      0.89         5



C:\Users\user\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
accuracy_score(y_test,y_pred)

0.8

In [18]:
from sklearn.ensemble import RandomForestClassifier

randf = RandomForestClassifier(n_estimators = 100,random_state=0)

randf.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [19]:
y_pred_RF = randf.predict(X_test)

In [20]:
confusion_matrix(y_test,y_pred_RF)

array([[0, 0],
       [1, 4]], dtype=int64)

In [21]:
accuracy_score(y_test,y_pred_RF)

0.8